code/chapter6/l7/lib/not_skull_web/router.ex
defmodule NotSkullWeb.Router do
  use NotSkullWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {NotSkullWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated_api do
    plug :accepts, ["json"]
    plug NotSkullWeb.Plugs.ValidateJWT
    plug NotSkullWeb.Plugs.MatchJWTUserId
  end

  scope "/", NotSkullWeb do
    pipe_through :browser
    get "/", WelcomeController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    post "/lobby/new", LobbyController, :new

    resources "/users", UserController

    live "/game", Game
  end

  scope "/api", NotSkullWeb.JsonApi do
    pipe_through :api

    post "/login", LoginController, :login
  end

  scope "/api", NotSkullWeb.JsonApi do
    pipe_through :api

    resources "/users", UserController, only: [:create]
  end

  scope "/api", NotSkullWeb.JsonApi do
    pipe_through :authenticated_api

    resources "/users", UserController, only: [:update]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NotSkullWeb.Telemetry
    end
  end
end

code/chapter6/l7/lib/not_skull/accounts/user.ex
defmodule NotSkull.Accounts.User do
  use NotSkull.Schema
  import Ecto.Changeset

  @optional_create_fields [:id, :inserted_at, :updated_at]
  @forbidden_update_fields [:id, :inserted_at, :updated_at]

  schema "users" do
    field(:email, :string)
    field(:name, :string)
    field(:password, :string)

    timestamps()
  end

  defp all_fields do
    __MODULE__.__schema__(:fields)
  end

  def create_changeset(params) do
    %__MODULE__{}
    |> cast(params, all_fields())
    |> validate_required(all_fields() -- @optional_create_fields)
    |> cleanup_email()
    |> hash_password()
    |> unique_constraint(:email)
  end

  def update_changeset(%__MODULE__{} = user, params) do
    user
    |> cast(params, all_fields() -- @forbidden_update_fields)
    |> validate_required(all_fields() -- @forbidden_update_fields)
    |> cleanup_email()
    |> hash_password()
    |> unique_constraint(:email)
  end

  defp cleanup_email(changeset) do
    changeset
    |> update_change(:email, &String.downcase/1)
    |> update_change(:email, &String.trim/1)
  end

  def hash_password(changeset) do
    changeset
    |> update_change(:password, &Argon2.hash_pwd_salt/1)
  end
end

code/chapter6/l7/lib/not_skull_web/controllers/json_api/user_controller.ex
# START:file_and_update
defmodule NotSkullWeb.JsonApi.UserController do
  @moduledoc false

  use NotSkullWeb, :controller

  alias NotSkull.Accounts

  # END:file_and_update
  alias NotSkull.ExternalServices.Email

  def create(conn, params) do
    case Accounts.create_user(params) do
      {:ok, user} ->
        Email.send_welcome(user)

        conn
        |> put_status(201)
        |> json(user_map_from_struct(user))

      {:error, error_changeset} ->
        conn
        |> put_status(422)
        |> json(errors_from_changset(error_changeset))
    end
  end

  # START:file_and_update
  def update(conn, params) do
    with {:ok, user} <- Accounts.get_user_by_id(params["id"]), # <label id="code.testing_phoenix.json_api.user_controller.update.with_statement"/>
         {:ok, updated_user} <- Accounts.update_user(user, params) do
      conn # <label id="code.testing_phoenix.json_api.user_controller.update.success_block"/>
      |> put_status(200)
      |> json(user_map_from_struct(updated_user))
    else
      {:error, error_changeset} ->
        conn # <label id="code.testing_phoenix.json_api.user_controller.update.error_handling"/>
        |> put_status(422)
        |> json(errors_from_changset(error_changeset))
    end
  end

  defp user_map_from_struct(user) do
    user
    |> Map.from_struct()
    |> Map.drop([:__struct__, :__meta__])
  end

  defp errors_from_changset(changeset) do
    serializable_errors =
      for {field, {message, _}} <- changeset.errors,
          do: %{"field" => to_string(field), "message" => message}

    %{errors: serializable_errors}
  end

  # END:file_and_update
end

code/chapter6/l7/lib/not_skull_web/controllers/user_controller.ex
#file path -> lib/not_skull_web/controllers/user_controller.ex
#add this code at the indicated place mentioned in comments of lib/not_skull_web/controllers/user_controller.ex
#in the playground widget
defmodule NotSkullWeb.UserController do
  use NotSkullWeb, :controller

  alias NotSkull.Accounts
  alias NotSkull.Accounts.User
  alias NotSkull.ExternalServices.Email

  def new(conn, _params) do
    user = User.create_changeset(%{})
    render(conn, "new.html", changeset: user)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        Email.send_welcome(user)

        conn
        |> put_session(:user_id, user.id)
        |> put_flash(:info, "Your account was created successfully!")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

code/chapter6/l7/lib/not_skull_web/views/user_view.ex
defmodule NotSkullWeb.UserView do
  use NotSkullWeb, :view
end

code/chapter6/l7/lib/not_skull_web/templates/user/edit.html.eex
<h1>Edit yourself</h1>

<%= form_for @changeset, Routes.user_path(@conn, :update, @user), fn f ->%>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      We found some problems when editing your account. Please try again.
    </div>
  <% end %>

  <%= label f, :email %>
  <%= error_tag f, :email %>
  <%= text_input f, :email %>

  <%= label f, :password %>
  <%= error_tag f, :password %>
  <%= password_input f, :password %>


  <div class="submit">
    <%= submit "Update user info" %>
  </div>

  <div>
    <%= link("Back to profile", to: Routes.user_path(@conn, :show, @user)) %>
  </div>
<% end %>

code/chapter6/l7/lib/not_skull_web/templates/user/new.html.eex
<h1>Create a new account</h1>

<%= form_for @changeset, Routes.user_path(@conn, :create), fn f -> %>
  <% if @changeset.action do %>
    <div class="alert alert-danger">
      We found some problems when creating your account. Please try again.
    </div>
  <% end %>

  <%= label f, :name%>
  <%= error_tag f, :name, id: "name-error" %>
  <%= text_input f, :name %>

  <%= label f, :email %>
  <%= error_tag f, :email, id: "email-error" %>
  <%= text_input f, :email %>

  <%= label f, :password %>
  <%= error_tag f, :password, id: "password-error" %>
  <%= password_input f, :password %>

  <div class="submit">
    <%= submit "Create account" %>
  </div>
<% end %>

code/chapter6/l7/lib/not_skull_web/templates/user/show.html.eex
<h1>Profile for: <%= @user.email %></h1>

<h2>Active games</h2>

<ul id="active-games">
  <%= for game_id <- NotSkull.ActiveGames.all() do %>
    <li><a href="<%= "/game?game_id=#{game_id}" %>"><%= game_id %></a></li>
  <% end %>
</ul>

<%= form_for @conn, Routes.lobby_path(@conn, :new), fn _f -> %>
  <div class="submit">
    <%= submit "New Game" %>
  </div>
<% end %>